name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest 
    # centos7 is not supported
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          working-directory: ./sync_ci        
  
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.15.5'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Make
        working-directory: ./sync_ci
        run: make

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.15.5'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        working-directory: ./sync_ci
        run: GO111MODULE=on go test -c ./pkg/parser && ./parser.test
